### ISSUE TITLE
Usage with TYPO3 7.2.0

### ISSUE THREAD

**Issue by utillity** [matoilic/t3chimp#40]
Hi, I have configured the API key, and was also able to choose the correct list in the plugin (so the API key seems to work). I have also added an extension template to the page and included the 2 t3chimp related templates. I don't really understand what the docs mean with "Do not forget to include the plugin's setup item in the containing page.", though.

But on the page I only see the following error message: Oops, an error occurred! Code: 2015053107201583b17cc9

since there are no details, I am not sure what the problem is.

**Comment by utillity** [comment]
I've disabled error-handling and now I see the following error-message:
$className "\MatoIlic\T3Chimp\MailChimp\Field\Email" must not start with a backslash.

**Comment by matoilic** [comment]
I've just pushed a new release to the TER that should fix this. See the changelog for all changes that might affect you https://github.com/matoilic/t3chimp/blob/master/CHANGELOG.md#250.

**Comment by utillity** [comment]
it's working now, thanks!!
