### ISSUE TITLE
Fatal error with guzzle

### ISSUE THREAD

**Issue by echavaillaz** [matoilic/t3chimp#44]
Hi,

I have a fatal error when I try to show the subscription form.

Warning: Uncaught exception 'TYPO3\CMS\Core\Error\Exception' with message 'PHP Warning: require(phar://guzzle.phar/autoloader.php): failed to open stream: phar error: invalid url or non-existent phar "phar://guzzle.phar/autoloader.php" in /.../typo3conf/ext/t3chimp/guzzle.phar line 3' in /.../typo3/sysext/core/Classes/Error/ErrorHandler.php:102 Stack trace: #0 /.../typo3conf/ext/t3chimp/guzzle.phar(3): TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'require(phar://...', '/home/httpd/...', 3, Array) #1 /.../typo3conf/ext/t3chimp/guzzle.phar(3): require() #2 /.../typo3conf/ext/t3chimp/Classes/MailChimp/MailChimpApi.php(5): require_once('/home/httpd/vho...') #3 /.../typo3/contrib/vendor/composer/ClassLoader.php(412): include('/home/httpd/vho...') #4 /.../typo3/sysext/core/Classes/Error/ErrorHandler.php on line 102

Fatal error: main(): Failed opening required 'phar://guzzle.phar/autoloader.php' (include_path='/.../typo3/contrib/vendor/pear/http_request2:/.../typo3/contrib/vendor/pear/pear_exception:.:/opt/atomic/atomic-php55/root/usr/share/pear:/opt/atomic/atomic-php55/root/usr/share/php') in /.../typo3conf/ext/t3chimp/guzzle.phar on line 3

Any idea how to fix it? Is it a bug?
Thanks

**Comment by dhoffmann1979** [comment]
Me too, i tried to find the problem but without success.....

**Comment by matoilic** [comment]
Seems like PHAR support is disabled in your PHP installation. Make sure to activate it http://php.net/manual/en/book.phar.php

**Comment by dhoffmann1979** [comment]
Phar support is enabled. see attached images. PHP Version is 5.5.9

![bildschirmfoto 2015-08-26 um 08 44 19](https://cloud.githubusercontent.com/assets/1279518/9487059/c5c9a6d2-4bce-11e5-9a05-09742a8f45b3.png)
![bildschirmfoto 2015-08-26 um 08 44 33](https://cloud.githubusercontent.com/assets/1279518/9487060/c81e5ac2-4bce-11e5-82cc-3deaba152664.png)

**Comment by echavaillaz** [comment]
The same for me...
![2015-08-26_1305](https://cloud.githubusercontent.com/assets/11553717/9491912/37510786-4bf3-11e5-9be1-4dc7dc67cb4c.png)

**Comment by davdenic** [comment]
same problem
phar is enabled in phpinfo
thanks

**Comment by matoilic** [comment]
should be fixed with #47
